version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - ./dist:/home/node/.n8n/custom/wgive-n8n:ro
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data: